### ISSUE TITLE
[backend] Сервис для генерации строковых данных

### ISSUE THREAD

**Issue by skqwk** [skqwk/DataGen#2]
## Задачи
- Написать базовую реализацию для сервиса генерации строковых данных
- Кратко прокомментировать принцип работы и входные данные

**Comment by IvanCherepanov** [comment]
Семен Антонович, посмотрите, пожалуйста

**Comment by IvanCherepanov** [comment]
Добавил забытые текстовые файлы в проект

**Comment by IvanCherepanov** [comment]
Семен Антонович, я перезалил
